apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "weihanli-top-tls-cert"
  namespace: "cert-manager"
  labels:
    app: "weihanli-top-tls-cert"
spec:
  commonName: "weihanli.top"
  secretName: "weihanli-top-tls-cert"
  dnsNames:
  - "weihanli.top"
  - "*.weihanli.top"
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt  
