{{ if .Values.issuer.create }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ include "alidns-webhook.name" . }}
    chart: {{ include "alidns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.issuer.secret_name }}
type: Opaque
data:
  {{- range $key, $val := .Values.issuer.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  labels:
    app: {{ include "alidns-webhook.name" . }}
    chart: {{ include "alidns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.issuer.email | quote }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        webhook:
          config:
            accessTokenSecretRef:
              key: accessKeyId
              name: {{ .Values.issuer.secret_name }}
            secretKeySecretRef:
              key: accessKeySecret
              name: {{ .Values.issuer.secret_name }}
            regionId: {{ .Values.issuer.regionId | quote }}
          groupName: {{ .Values.groupName }}
          solverName: alidns-solver
{{ if .Values.issuer.createCert }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "alidns-webhook.certname" . }}
  labels:
    app: {{ include "alidns-webhook.name" . }}
    chart: {{ include "alidns-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  commonName: {{ .Values.issuer.host | quote }}
  dnsNames:
  - {{ .Values.issuer.host | quote }}
  - '*.{{ .Values.issuer.host }}'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: {{ include "alidns-webhook.certname" . }}
{{ end }}
{{ end }}
